#FROM node:lts-alpine
FROM node:12.18.2-stretch-slim

# install simple http server for serving static content
RUN npm install -g http-server

WORKDIR /app

COPY ./package*.json ./

RUN npm install
#shouldn't need to install vue-cli
#RUN npm install -g @vue/cli

COPY . .

#RUN npm run build

CMD ["npm", "run", "serve"]